### ISSUE TITLE
go install doesn't install latest

### ISSUE THREAD

**Issue by juliusmarminge** [mattrobenolt/ps-http-sim#9]
Latest publish on go in 0.0.3 in november: https://pkg.go.dev/github.com/mattrobenolt/ps-http-sim#section-readme

**Comment by mattrobenolt** [comment]
I'm not actually sure what updates that, since you don't upload packages there, they are pulled through their proxy. You can explicitly `go install github.com/mattrobenolt/ps-http-sim@v0.0.7` tho and it works.

After I did that, I was able to do `@latest` and it works, but their website still doesn't show newer version. There used to be a button to trigger a manual refresh of the metadata that I can't find anymore.

**Comment by mattrobenolt** [comment]
Ok, they should be updated now. TIL you can do `$ curl -XPOST https://pkg.go.dev/fetch/github.com/mattrobenolt/ps-http-sim@v0.0.7` to force it to update now.

I'll add this to the CI pipeline to run this as the last step.

But everything looks good now. 
<img width="325" alt="image" src="https://github.com/mattrobenolt/ps-http-sim/assets/375744/8db03e83-026f-476b-9470-7d2af3eb2d8a">

**Comment by mattrobenolt** [comment]
lol https://github.com/search?q=%22https%3A%2F%2Fpkg.go.dev%2Ffetch%2F%22&type=code
